services:
  carvekit_api:
    build:
      dockerfile: Dockerfile.cuda
      context: .
    ports:
      - "5000:5000"  # 5000
    environment:
      - CARVEKIT_PORT=5000
      - CARVEKIT_HOST=0.0.0.0
      - CARVEKIT_SEGMENTATION_NETWORK=u2net  # can be u2net, basnet, deeplabv3
      - CARVEKIT_PREPROCESSING_METHOD=none # can be none, stub
      - CARVEKIT_POSTPROCESSING_METHOD=fba # can be none, fba
      - CARVEKIT_DEVICE=cuda # can be cuda (req. cuda docker image), cpu
      - CARVEKIT_BATCH_SIZE_SEG=5 #  Number of images processed per one segmentation nn call. NOT USED IF WEB API IS USED
      - CARVEKIT_BATCH_SIZE_MATTING=1  # Number of images processed per one matting nn call. NOT USED IF WEB API IS USED
      - CARVEKIT_SEG_MASK_SIZE=320  # The size of the input image for the segmentation neural network.
      - CARVEKIT_MATTING_MASK_SIZE=2048   # The size of the input image for the matting neural network.

      - CARVEKIT_AUTH_ENABLE=1  # Enables authentication by tokens
      # Tokens will be generated automatically every time the container is restarted if these ENV is not set.
      #- CARVEKIT_ADMIN_TOKEN=admin
      #- CARVEKIT_ALLOWED_TOKENS=test_token1,test_token2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]