name: Docker images

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./
          file: "./Dockerfile.cpu"
          tags: |
            anodev/carvekit:latest-cpu
            anodev/carvekit:${{ env.RELEASE_VERSION }}-cpu
      - name: Build and push cuda
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./
          file: "./Dockerfile.cuda"
          tags: |
            anodev/carvekit:latest-cuda
            anodev/carvekit:${{ env.RELEASE_VERSION }}-cuda