# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Python

on:
  push:
    branches: [ pre-release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install -r requirements.txt
    - name: Setup
      run: |
        cd tools && echo "all" | python setup.py
    - name: Test
      run: |
        cd tests && chmod +x ./run_tests.sh && ./run_tests.sh
